### ISSUE TITLE
ecef2ned: "alt_ref" probably not working

### ISSUE THREAD

**Issue by angelo79** [NavPy/NavPy#16]
I probably didn't manage to use the ecef2ned properly: it seems that the "alt_ref" values have no effect on the result.
To replicate the issue:
navpy.ecef2ned([4833331, 962871, 4051597], 39.747655, 11.239529, 111111111, 'deg', 'f', 'wgs84')
navpy.ecef2ned([4833331, 962871, 4051597], 39.747655, 11.239529, -111111111, 'deg', 'f', 'wgs84')
navpy.ecef2ned([4833331, 962871, 4051597], 39.747655, 11.239529, 0, 'deg', 'f', 'wgs84')
all bear the same result:
-3.60529321e+04,   2.33426743e+03,  -6.37983872e+06

I hope I'm mistaken since this function would be very helpful to me.
Also "alt_unit" and "model" seems to have no effects.

I have a very limited python (and programming) experience, so please excuse me if I overlooked something.
Thanks.

**Comment by adhika** [comment]
The description on the code is perhaps unclear. The function ecef2ned
converts a relative vector in the ECEF frame to a local NED frame. It is
not intended to convert an ECEF position to an NED position relative to the
reference LLA coordinate. We should remove alt_ref input from the input
argument as well.

To achieve what you want, you could first convert the ECEF position to LLA
and then use the function navpy.lla2ned.
Example:

>> ecef = [-2517695.49194843, -4667336.38167972,  3531835.03921866]
>> lla = navpy.ecef2lla(ecef)
>> lla
(33.841199999999994, -118.3437, 8.9411000004038215)

>> navpy.lla2ned(lla[0], lla[1], lla[2], 33, -118, 0)
array([ 93347.89721335, -31811.46901301,    755.97947485])

>> navpy.lla2ned(lla[0],lla[1],lla[2],33,-118, 20)
array([ 93347.89721335, -31811.46901301,    775.97947485])

>> navpy.lla2ned(lla[0],lla[1],lla[2],33,-118, 30)
array([ 93347.89721335, -31811.46901301,    785.97947485])

**Comment by angelo79** [comment]
Thank you adhika for the fast support; it seems I misunderstood what the ecef2ned function actually does, and from the description "The center of the NED coordiante is given by lat_ref, lon_ref, and alt_ref" I mistakenly  thought that NED was function of alt_ref. 
I was looking exactly for what you described, that is converting an ECEF position to a NED position relative to LLA reference coordinates.
If it could be helpful for someone in my same situation, I found the "pymap3d.ecef2ned" function does exactly that, taking ECEF x,y,z and a reference LLA and returning a NED vector.
Thank you again for your help and sorry for my mistake.
